accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

portfolio_mngmt/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomePage


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePage.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('home/', views.ProductTemplateView.as_view(), name='home'),
    path('product_detail/<slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('natural_product_list/', views.NaturalProductListView.as_view(), name='products_list'),
    path('natural_identical_product_list/', views.NaturalIdenticalProductListView.as_view(), name='ni_products_list'),
    path('create/', views.ProductCreateView.as_view(), name='create'),
    path('search_list/<name>/', views.ProductSearchListView.as_view(), name='search_list'),
    path('ni_search_list/<name>/', views.NIProductSearchListView.as_view(), name='ni_search_list'),
    path('uni_search_list/<name>/', views.UniversalSearchListView.as_view(), name='uni_search_list'),
    path('delete/<int:pk>/', views.ProductDeleteView.as_view(), name='delete'),
    path('update/<int:pk>/', views.ProductUpdateView.as_view(), name='update'),
    path('quantity_update/<slug>/', views.QuantityUpdateView.as_view(), name='quantity_update'),
    path('filter_products/', views.filter, name='filter'),
    path('filter_list/<flavour_key>/<alcohol_content>/<production_site>/<solubility>/', views.FilterListView.as_view(), name='filter_list'),
    path('ni_filter_products/', views.ni_filter, name='ni_filter'),
    path('ni_filter_list/<flavour_key>/<alcohol_content>/<production_site>/<solubility>/', views.NIFilterListView.as_view(), name='ni_filter_list'),
    path('export/<qset>/', views.export_to_xlsx, name='export'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans&display=swap" rel="stylesheet">
    
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css"> 
    <title>{% block title %}Base{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-light bg-transparent">
        <a class="navbar-brand" href="{% url 'products:home' %}">
          <img src="{% static 'images/symrise_logo.jpg' %}" width="180" height="50" class="d-inline-block align-top" alt="" loading="lazy">
        </a>
        <ul class="nav justify-content-end">
            {% if user.is_authenticated %}
              {% block expiry_alert%}{% endblock %}
              <li class="nav-item">
                <a class="btn btn-outline-danger" href="{% url 'accounts:logout' %}">Log Out</a>
              </li>
            {% else %}
            <li class="nav-item">
                <a class="btn btn-outline-success" href="{% url 'accounts:login' %}">Log In</a>
            </li>
            {% endif %}    
        </ul>
    </nav>

    {% block body %}
    
    {% endblock %}

<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>


<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
  <script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
  <script>
    $(document).ready(function() {
    $('.datepicker').datepicker();
      });
    </script>


</body>
</html>