accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

portfolio_mngmt/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomePage


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePage.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('home/', views.ProductTemplateView.as_view(), name='home'),
    path('product_detail/<slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('natural_product_list/', views.NaturalProductListView.as_view(), name='products_list'),
    path('natural_identical_product_list/', views.NaturalIdenticalProductListView.as_view(), name='ni_products_list'),
    path('create/', views.ProductCreateView.as_view(), name='create'),
    path('search_list/<name>/', views.ProductSearchListView.as_view(), name='search_list'),
    path('ni_search_list/<name>/', views.NIProductSearchListView.as_view(), name='ni_search_list'),
    path('uni_search_list/<name>/', views.UniversalSearchListView.as_view(), name='uni_search_list'),
    path('delete/<int:pk>/', views.ProductDeleteView.as_view(), name='delete'),
    path('update/<int:pk>/', views.ProductUpdateView.as_view(), name='update'),
    path('quantity_update/<slug>/', views.QuantityUpdateView.as_view(), name='quantity_update'),
    path('filter_products/', views.filter, name='filter'),
    path('filter_list/<flavour_key>/<alcohol_content>/<production_site>/<solubility>/', views.FilterListView.as_view(), name='filter_list'),
    path('ni_filter_products/', views.ni_filter, name='ni_filter'),
    path('ni_filter_list/<flavour_key>/<alcohol_content>/<production_site>/<solubility>/', views.NIFilterListView.as_view(), name='ni_filter_list'),
    path('export/<qset>/', views.export_to_xlsx, name='export'),
]

products/forms.py
from django import forms
from .models import Product

from functools import partial
DateInput = partial(forms.DateInput, {'class': 'datepicker'})


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        widgets = {
        'expiry_date': DateInput(),
        'order_date': DateInput(),
        'arrival_date': DateInput(),
        }

class QuantityForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['quantity']


class FilterForm(forms.Form):

    pd_list = Product.objects.all()
    flv_key = []
    sol = []
    site = []
    for pd in pd_list:
        if pd.is_natural():
            li = pd.flavour_key.split('; ')
            for item in li:
                flv_key.append((item, item))
            if pd.solubility != '':
                sol.append((pd.solubility, pd.solubility))
            site.append((pd.production_site, pd.production_site))
    
    flv_key = list(sorted(set(flv_key)))
    flv_key.insert(0, ('Select all','Select all'))

    sol = list(sorted(set(sol)))
    sol.insert(0, ('Select all','Select all'))

    alc = [
        ('all', 'Select all'),
        ('less', 'Less than 0.1'),
        ('greater', 'Greater than 0.1'),
    ]
    site = list(sorted(set(site)))
    site.insert(0, ('Select all','Select all'))

    flavour_key = forms.MultipleChoiceField(choices=flv_key)
    alcohol_content = forms.ChoiceField(choices=alc,label='Alcohol content ( in % )', widget=forms.RadioSelect())
    production_site = forms.MultipleChoiceField(choices=site,widget=forms.CheckboxSelectMultiple(attrs={'id':'pro'}))
    solubility = forms.MultipleChoiceField(choices=sol,widget=forms.CheckboxSelectMultiple(attrs={'id':'sol'}))

    flavour_key.widget.attrs.update({'class':'form-control', 'size':'10', 'id':'flv'})
    alcohol_content.widget.attrs.update({'id':'alc'})
    

class NIFilterForm(forms.Form):

    pd_list = Product.objects.all()
    flv_key = []
    sol = []
    site = []
    for pd in pd_list:
        if pd.is_natural() == False:
            li = pd.flavour_key.split('; ')
            for item in li:
                flv_key.append((item, item))
            if pd.solubility != '':
                sol.append((pd.solubility, pd.solubility))
            site.append((pd.production_site, pd.production_site))
    
    flv_key = list(sorted(set(flv_key)))
    flv_key.insert(0, ('Select all','Select all'))

    sol = list(sorted(set(sol)))
    sol.insert(0, ('Select all','Select all'))

    alc = [
        ('all', 'Select all'),
        ('less', 'Less than 0.1'),
        ('greater', 'Greater than 0.1'),
    ]
    site = list(sorted(set(site)))
    site.insert(0, ('Select all','Select all'))

    flavour_key = forms.MultipleChoiceField(choices=flv_key)
    alcohol_content = forms.ChoiceField(choices=alc,label='Alcohol content ( in % )', widget=forms.RadioSelect())
    production_site = forms.MultipleChoiceField(choices=site,widget=forms.CheckboxSelectMultiple(attrs={'id':'pro'}), required=True)
    solubility = forms.MultipleChoiceField(choices=sol,widget=forms.CheckboxSelectMultiple(attrs={'id':'sol'}))

    flavour_key.widget.attrs.update({'class':'form-control', 'size':'10', 'id':'flv'})
    alcohol_content.widget.attrs.update({'id':'alc'})
    
    

products/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, TemplateView, UpdateView, DeleteView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import Product
from django.urls import reverse, reverse_lazy
from datetime import datetime
from .forms import ProductForm, QuantityForm, FilterForm, NIFilterForm
from django.http import HttpResponseRedirect, HttpResponse
import re
from openpyxl import Workbook
from django.contrib import messages


# Create your views here.

class ProductTemplateView(LoginRequiredMixin, TemplateView):

    template_name = 'products/products_home.html'

    def post(self, request, *args, **kwargs):
        six_d_code = []
        for pd in Product.objects.all():
            six_d_code.append(str(pd.six_digit_code))

        if request.POST.get('search') in six_d_code:
            return redirect(reverse('products:product_detail', kwargs={'slug':request.POST.get('search')}))
        elif len(Product.objects.filter(name__icontains=request.POST.get('search'))):
            return redirect(reverse('products:uni_search_list', kwargs={'name':request.POST.get('search')}))
        else:
            messages.error(request, 'The item(s) you searched for do(es) not exist.')
            return redirect(reverse('products:home'))
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pd_list = Product.objects.all()
        alert = False
        for pd in pd_list:
            if pd.expiry_alert():
                alert = True
                break
        num = 0
        for pd in pd_list:
            if pd.expiry_alert():
                num += 1
            
        context['pd_list'] = Product.objects.all()
        context['alert'] = alert
        context['num'] = num
        return context


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'products/products_detail.html'


class NaturalProductListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'products/products_list.html'
    context_object_name = 'pd_list'

    def post(self, request, *args, **kwargs):
        if request.POST.get('submit') == 'Search':
            return redirect(reverse('products:search_list', kwargs={'name':request.POST.get('search')}))
        
        if request.POST.get('submit') == 'Export':
            return redirect(reverse('products:export', kwargs={'qset':'natural'}))


class NaturalIdenticalProductListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'products/ni_products_list.html'
    context_object_name = 'pd_list'

    def post(self, request, *args, **kwargs):
        if request.POST.get('submit') == 'Search':
            return redirect(reverse('products:ni_search_list', kwargs={'name':request.POST.get('search')}))
        
        if request.POST.get('submit') == 'Export':
            return redirect(reverse('products:export', kwargs={'qset':'ni'}))


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'products/product_create_form.html'


class UniversalSearchListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'products/uni_search_list.html'
    context_object_name = 'pd_list'

    def get_queryset(self):
        search_term = self.kwargs.get('name')
        if search_term.isdigit():
            queryset = Product.objects.filter(six_digit_code__iexact=self.kwargs.get('name'))
        else:
            queryset = Product.objects.filter(name__icontains=self.kwargs.get('name'))
        
        if len(queryset) == 0:
            messages.error(self.request, 'The item(s) you searched for do(es) not exist.')

        return queryset
    
    def post(self, request, *args, **kwargs):
        if request.POST.get('submit') == 'Search':
            return redirect(reverse('products:uni_search_list', kwargs={'name':request.POST.get('search')}))


class ProductSearchListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'products/products_list.html'
    context_object_name = 'pd_list'

    def get_queryset(self):
        search_term = self.kwargs.get('name')
        if search_term.isdigit():
            queryset = Product.objects.filter(six_digit_code__iexact=self.kwargs.get('name')).filter(legal_name__icontains='natural')
        else:
            queryset = Product.objects.filter(name__icontains=self.kwargs.get('name')).filter(legal_name__icontains='natural')
        
        if len(queryset) == 0:
            messages.error(self.request, 'The item(s) you searched for do(es) not exist.')
        
        return queryset
    
    def post(self, request, *args, **kwargs):
        if request.POST.get('submit') == 'Search':
            return redirect(reverse('products:search_list', kwargs={'name':request.POST.get('search')}))
        
        if request.POST.get('submit') == 'Export':
            return redirect(reverse('products:export', kwargs={'qset':'natural'}))

class NIProductSearchListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'products/ni_products_list.html'
    context_object_name = 'pd_list'

    def get_queryset(self):
        search_term = self.kwargs.get('name')
        if search_term.isdigit():
            queryset = Product.objects.filter(six_digit_code__iexact=self.kwargs.get('name')).exclude(legal_name__icontains='natural')
        else:
            queryset = Product.objects.filter(name__icontains=self.kwargs.get('name')).exclude(legal_name__icontains='natural')
        
        if len(queryset) == 0:
            messages.error(self.request, 'The item(s) you searched for do(es) not exist.')
        
        return queryset
    
    def post(self, request, *args, **kwargs):
        if request.POST.get('submit') == 'Search':
            return redirect(reverse('products:ni_search_list', kwargs={'name':request.POST.get('search')}))
        
        if request.POST.get('submit') == 'Export':
            return redirect(reverse('products:export', kwargs={'qset':'ni'}))


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('products:home')


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'products/product_update_form.html'

class QuantityUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = QuantityForm
    template_name = 'products/quantity_update_form.html'


@login_required
def filter(request):

    if request.method == 'POST':
        form = FilterForm(request.POST)

        if form.is_valid():
            f = form.cleaned_data.get('flavour_key')
            a = form.cleaned_data.get('alcohol_content')
            p = form.cleaned_data.get('production_site')
            s = form.cleaned_data.get('solubility')

            return HttpResponseRedirect(reverse('products:filter_list', kwargs={'flavour_key':f, 'alcohol_content':a, 'production_site':p, 'solubility':s }))

    else:
        context = {}
        form = FilterForm()
        context['form'] = form
        return render(request, 'products/filter.html', context)


class FilterListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'products/filter_list.html'
    context_object_name = 'filter_pd'

    def get_queryset(self):
        flv = self.kwargs.get('flavour_key')
        alc = self.kwargs.get('alcohol_content')
        prod = self.kwargs.get('production_site')
        sol = self.kwargs.get('solubility')

        flv_ls = re.findall(r'[A-Za-z]+\s[A-Za-z]+|[A-Za-z]+', flv)
        sol_ls = re.findall(r'[A-Za-z]+\s[a-z]+', sol)
        prod_ls = re.findall(r'[A-Za-z]+\s[A-Za-z]+|[A-Za-z]+',prod)

        if 'Select all' in flv_ls:
            flv_qset = Product.objects.all()
        else:
            flv_qset = Product.objects.filter(flavour_key__icontains=flv_ls[0])
            for i in range(1,len(flv_ls)):
                flv_qset = flv_qset | Product.objects.filter(flavour_key__icontains=flv_ls[i])

        if 'Select all' in prod_ls:
            prod_qset = Product.objects.all()
        else:
            prod_qset = Product.objects.filter(production_site__in=prod_ls)
        
        if 'Select all' in sol_ls:
            sol_qset = Product.objects.all()
        else:
            sol_qset = Product.objects.filter(solubility__in=sol_ls)


        if alc == 'less':
            alc_qset = Product.objects.filter(alcohol_content__lte=0.1)
        elif alc == 'greater':
            alc_qset = Product.objects.filter(alcohol_content__gte=0.1)
        else:
            alc_qset = Product.objects.all()

        queryset = Product.objects.all().intersection(flv_qset, prod_qset, sol_qset, alc_qset)
        
        return queryset    


@login_required
def ni_filter(request):

    if request.method == 'POST':
        form = NIFilterForm(request.POST)

        if form.is_valid():
            f = form.cleaned_data.get('flavour_key')
            a = form.cleaned_data.get('alcohol_content')
            p = form.cleaned_data.get('production_site')
            s = form.cleaned_data.get('solubility')

            return HttpResponseRedirect(reverse('products:ni_filter_list', kwargs={'flavour_key':f, 'alcohol_content':a, 'production_site':p, 'solubility':s }))

    else:
        context = {}
        form = NIFilterForm()
        context['form'] = form
        return render(request, 'products/ni_filter.html', context)


class NIFilterListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'products/ni_filter_list.html'
    context_object_name = 'filter_pd'

    def get_queryset(self):
        flv = self.kwargs.get('flavour_key')
        alc = self.kwargs.get('alcohol_content')

products/templates/products/filter_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Natural Flavours{% endblock %}

{% block body %}



<div class="container">
   
    <div id="carouselExampleSlidesOnly" class="carousel slide carousel-fade mycarousal" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
              <img src="{% static 'images/bev1.jpg' %}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/bev.jpg' %}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/cake.jpg' %}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/egg.jpg' %}" class="d-block w-100" alt="...">
          </div>
        </div>
    </div>

    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a href="{% url 'products:create' %}" class="btn btn-outline-success">Add Product</a>
          </li>
          <li class="nav-item filter">
            <a href="{% url 'products:filter' %}" class="btn btn-outline-success">Filter</a>
          </li>
        </ul>
      </div>
    </nav>
    

    <ul class="list-group list-group-flush">
        {% for pd in filter_pd %}
        {% if pd.is_natural %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
        <a href="{% url 'products:product_detail' slug=pd.slug %}">{{ pd.six_digit_code }} {{ pd.name }}</a>
        
        {% if pd.expiry_alert %}
        <span>
          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-exclamation-circle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 4a.905.905 0 0 0-.9.995l.35 3.507a.552.552 0 0 0 1.1 0l.35-3.507A.905.905 0 0 0 8 4zm.002 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
          </svg>
        </span>
        {% endif %}
        </li>
        {% endif %}
        {% endfor %}
    </ul>

</div>

<style>
    a:hover{
        text-decoration: none;
        color: green;
    }
    .mycarousal{
        margin-bottom: 10px;
    }
    a{
        color: black;
    }
    .list-group{
        margin-top: 20px;
    }

    .carousel-item{
    height: 250px;
    } 
    .filter{
      margin-left: 15px;
    }

</style>

{% endblock %}

products/templates/products/ni_filter_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}NI Flavours{% endblock %}

{% block body %}



<div class="container">
   
    <div id="carouselExampleSlidesOnly" class="carousel slide carousel-fade mycarousal" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
              <img src="{% static 'images/bev1.jpg' %}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/bev.jpg' %}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/cake.jpg' %}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/egg.jpg' %}" class="d-block w-100" alt="...">
          </div>
        </div>
    </div>

    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a href="{% url 'products:create' %}" class="btn btn-outline-success">Add Product</a>
              </li>
              <li class="nav-item filter">
                <a href="{% url 'products:ni_filter' %}" class="btn btn-outline-success">Filter</a>
              </li>
        </ul>
      </div>
    </nav>
    

    <ul class="list-group list-group-flush">
        {% for pd in filter_pd %}
        {% if not pd.is_natural %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
        <a href="{% url 'products:product_detail' slug=pd.slug %}">{{ pd.six_digit_code }} {{ pd.name }}</a>
        
        {% if pd.expiry_alert %}
        <span>
          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-exclamation-circle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 4a.905.905 0 0 0-.9.995l.35 3.507a.552.552 0 0 0 1.1 0l.35-3.507A.905.905 0 0 0 8 4zm.002 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
          </svg>
        </span>
        {% endif %}
        </li>
        {% endif %}
        {% endfor %}
    </ul>

</div>

<style>
    a:hover{
        text-decoration: none;
        color: green;
    }
    .mycarousal{
        margin-bottom: 10px;
    }
    a{
        color: black;
    }
    .list-group{
        margin-top: 20px;
    }

    .carousel-item{
    height: 250px;
    } 
    .filter{
      margin-left: 15px;
    }

</style>

{% endblock %}

products/templates/products/ni_products_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}NI Flavours{% endblock %}

{% block body %}



<div class="container">
   
    <div id="carouselExampleSlidesOnly" class="carousel slide carousel-fade mycarousal" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
              <img src="{% static 'images/bev1.jpg' %}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/bev.jpg' %}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/cake.jpg' %}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/egg.jpg' %}" class="d-block w-100" alt="...">
          </div>
        </div>
    </div>
    
    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a href="{% url 'products:create' %}" class="btn btn-outline-success">Add Product</a>
              </li>
              <li class="nav-item filter">
                <a href="{% url 'products:ni_filter' %}" class="btn btn-outline-success">Filter</a>
              </li>
              <li class="nav-item filter">
                <form method="post">
                  {% csrf_token %}
                  <input type="submit" value="Export" class="btn btn-outline-success" name="submit">
                </form>
                </li>
          </ul>
          <form class="form-inline my-2 my-lg-0" method="POST">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search">
            <input type="submit" value="Search" class="btn btn-outline-success my-2 my-sm-0" name="submit">
          </form>
        </div>
      </nav>
    
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}

    <ul class="list-group list-group-flush">
        {% for pd in pd_list %}
        {% if not pd.is_natural %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
        <a href="{% url 'products:product_detail' slug=pd.slug %}">{{ pd.six_digit_code }} {{ pd.name }}</a>
        
        {% if pd.expiry_alert %}
        <span>
          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-exclamation-circle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 4a.905.905 0 0 0-.9.995l.35 3.507a.552.552 0 0 0 1.1 0l.35-3.507A.905.905 0 0 0 8 4zm.002 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
          </svg>
        </span>
        {% endif %}
        </li>
        {% endif %}
        {% endfor %}
    </ul>

</div>

<style>
    a:hover{
        text-decoration: none;
        color: green;
    }
    .mycarousal{
        margin-bottom: 10px;
    }
    a{
        color: black;
    }
    .list-group{
        margin-top: 20px;
    }

    .carousel-item{
    height: 250px;
    } 
    .filter{
      margin-left: 15px;
    }

</style>

{% endblock %}

products/templates/products/products_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Natural Flavours{% endblock %}

{% block body %}

<div class="container">
   
    <div id="carouselExampleSlidesOnly" class="carousel slide carousel-fade mycarousal" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
              <img src="{% static 'images/bev1.jpg' %}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/bev.jpg' %}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/cake.jpg' %}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/egg.jpg' %}" class="d-block w-100" alt="...">
          </div>
        </div>
    </div>
    
    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a href="{% url 'products:create' %}" class="btn btn-outline-success">Add Product</a>
              </li>
              <li class="nav-item filter">
                <a href="{% url 'products:filter' %}" class="btn btn-outline-success">Filter</a>
              </li>
              <li class="nav-item filter">
              <form method="post">
                {% csrf_token %}
                <input type="submit" value="Export" class="btn btn-outline-success" name="submit">
              </form>
              </li>
          </ul>
          <form class="form-inline my-2 my-lg-0" method="POST">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search">
            <input type="submit" value="Search" class="btn btn-outline-success my-2 my-sm-0" name="submit">
          </form>
        </div>
      </nav>
    
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}

    <ul class="list-group list-group-flush">
        {% for pd in pd_list %}
        {% if pd.is_natural %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
        <a href="{% url 'products:product_detail' slug=pd.slug %}">{{ pd.six_digit_code }} {{ pd.name }}</a>
        
        {% if pd.expiry_alert %}
        <span>
          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-exclamation-circle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 4a.905.905 0 0 0-.9.995l.35 3.507a.552.552 0 0 0 1.1 0l.35-3.507A.905.905 0 0 0 8 4zm.002 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
          </svg>
        </span>
        {% endif %}
        </li>
        {% endif %}
        {% endfor %}
    </ul>

</div>

<style>
    a:hover{
        text-decoration: none;
        color: green;
    }
    .mycarousal{
        margin-bottom: 10px;
    }
    a{
        color: black;
    }
    .list-group{
        margin-top: 20px;
    }

    .carousel-item{
    height: 250px;
    }
    .filter{
      margin-left: 15px;
    }

</style>

{% endblock %}